name: Print Time

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  print_time:
    runs-on: ubuntu-latest
    steps:
    - name: Print Time
      uses: python:3.8
      with:
        python-version: 3.8
      run: |
        import time
        while True:
          print(time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime()))
          time.sleep(5)
